version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Cleaning and installing dependencies"
      - npm ci || npm install

  build:
    commands:
      - echo "Running production build"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
